startProposal work
giuliano2014/alyra-project-3 pull request #14
Opened 2023-03-09 14:13 UTC by rembeuch

2023-03-09 20:40 UTC, giuliano2014 requested changes

2023-03-09 20:40 UTC, giuliano2014 commented on client/src/components/Owner/OwnerContainer.jsx
>        <div>
@rembeuch 
Tu devrais créer un nouveau composant genre `ProposalsRegistering`.
Et y mettre le html avec la logique que tu as créé dans le `OwnerContainer`, `const [error, setError] = useState()` et ta fonction `StartProposal `.
Cela permettrait de garder un découpage propre, comme j'ai fait pour le composant `AddVoter`.
;-)

2023-03-09 20:40 UTC, giuliano2014 commented on client/src/components/Owner/OwnerContainer.jsx
> +  const StartProposal = async e => {
@rembeuch 
Comme tu utilises `async` & `await` le code devrait être plutôt, comme cela :
```suggestion
  const startProposal = async () => {
    try {
      await contract.methods.startProposalsRegistering().send({ from: accounts[0] });
    } catch (error) {
      setError(error.message.match(/revert (.*)/)[1]);
    }
  };
```
Ou version avec des promises 

```suggestion
  const startProposal = () => {
    contract.methods.startProposalsRegistering().call({ from: accounts[0] })
      .then(result => {
        return contract.methods.startProposalsRegistering().send({ from: accounts[0] });
      })
      .catch(error => {
        setError(error.message.match(/revert (.*)/)[1]);
      });
  };
```

Je pense que la version 1 est plus lisible et propre.

Dans ta version, tu mélanges `await` avec `callback` et `function` avec `arrow function`.
:v:

2023-03-10 10:19 UTC, rembeuch commented on client/src/components/Owner/OwnerContainer.jsx
> +  const StartProposal = async e => {
il faut malheureusement utiliser la 2ème méthode car sans le .call on ne récupère pas l'erreur du require.

2023-03-10 11:31 UTC, giuliano2014 approved these changes

2023-03-10 11:45 UTC, giuliano2014 approved these changes

2023-03-10 11:45 UTC, merged